---
kind: pipeline
name: default
steps:
  - name: dockerx
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      experimental: true
      username: jmcloud
      password:
        from_secret: JMC_DOCKER_PASSWORD
      repo: jmcloud/${DRONE_REPO_NAME/_/-}
      auto_tag: true
      platforms:
        - linux/arm64/v8
        - linux/amd64

  - name: Slack notification
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: ci-cd
      template: >
        {{#success build.status}}
          Publish for `{{repo.name}}/{{build.ref}}` succeeded.
          {{build.link}}
        {{else}}
          Publish for `{{repo.name}}/{{build.ref}}` failed.
          {{build.link}}
        {{/success}}
    when:
      ref:
        - refs/heads/master
        - refs/tags/*
      status:
        - success
        - failure
