FROM python:3.8-alpine
COPY . /opt/ansible/
WORKDIR /opt/ansible/
RUN \
  apk add \
    --no-cache \
    jq \
    bash

RUN \
  apk add \
    --no-cache \
    --virtual build-dependencies \
    git \
    gcc \
    musl-dev \
    libffi-dev \
    openssl-dev \
  && pip install \
    ansible==2.9.2 \
    f5-sdk==3.0.21 \
    deepdiff \
  && ansible-galaxy install -fr requirements.yml \
  && mv /opt/ansible/roles/veselahouba.f5_ansible /opt/ansible/roles/f5 \
  && ansible-galaxy collection install https://f5-ansible.s3.amazonaws.com/collections/f5networks-f5_modules-devel.tar.gz -p ./collections \
  && ln -s /opt/ansible/roles collections/ansible_collections/f5networks/f5_modules/roles \
  && apk del build-dependencies \
  && rm -rf /var/cache/apk/*
CMD ansible-playbook
