FROM python:3.8-alpine
COPY . /opt/ansible/
WORKDIR /opt/ansible/
ENV PIP_CERT=/etc/ssl/certs/ca-certificates.crt
RUN \
  update-ca-certificates && \
  apk --no-cache add \
    git \
    jq \
    bash \
    gcc \
    musl-dev \
    libffi-dev \
    openssl-dev && \
  pip install \
    ansible \
    f5-sdk && \
  ansible-galaxy install -fr requirements.yml && \
  ansible-galaxy collection install https://f5-ansible.s3.amazonaws.com/collections/f5networks-f5_modules-1.4.0-devel.tar.gz -p ./collections && \
  ln -s /opt/ansible/roles collections/ansible_collections/f5networks/f5_modules/roles && \
  apk del \
    git \
    gcc \
    musl-dev \
    libffi-dev \
    openssl-dev && \
  rm -rf /var/cache/apk/*
CMD ansible-playbook
